# Generated by Django 3.1.7 on 2021-05-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main_page',
            fields=[
                ('Food_id', models.AutoField(primary_key=True, serialize=False)),
                ('Food_type', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('slug', models.CharField(max_length=130)),
                ('Link_of_image', models.URLField()),
            ],
        ),
    ]
