# Generated by Django 3.1.7 on 2021-05-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadCSV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('PhoneNo', models.CharField(max_length=20)),
                ('Age', models.IntegerField()),
                ('Password', models.CharField(max_length=50)),
                ('Weight', models.FloatField()),
                ('Gender', models.CharField(max_length=50)),
                ('WorkType', models.TextField(max_length=100)),
            ],
        ),
    ]
