# Generated by Django 3.1.7 on 2021-05-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food_diary',
            fields=[
                ('mfg_code', models.CharField(max_length=20)),
                ('food_id', models.IntegerField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=700)),
                ('food_type', models.CharField(max_length=105)),
                ('calories', models.IntegerField()),
                ('protein', models.FloatField()),
                ('fats', models.FloatField()),
                ('carbohydrates', models.FloatField()),
                ('link_of_image', models.URLField(max_length=2000)),
                ('link_of_recipie', models.URLField(max_length=800)),
                ('purchasing_link', models.URLField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Temporary',
            fields=[
                ('food_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('calories', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('meal_type', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction_det',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('food_name', models.CharField(max_length=30)),
                ('calories', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('meal_type', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Unsaved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('food_name', models.CharField(max_length=30)),
                ('calories', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('meal_type', models.CharField(max_length=25)),
            ],
        ),
    ]
