# Generated by Django 3.1.7 on 2021-05-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase_det',
            fields=[
                ('email_id', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('mfg_code', models.CharField(max_length=20)),
                ('food_id', models.IntegerField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=30)),
                ('calories', models.IntegerField()),
                ('protein', models.FloatField()),
                ('fats', models.FloatField()),
                ('carbohydrates', models.FloatField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Temporary_purchase',
            fields=[
                ('mfg_code', models.CharField(max_length=20)),
                ('food_id', models.IntegerField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=30)),
                ('calories', models.IntegerField()),
                ('protein', models.FloatField()),
                ('fats', models.FloatField()),
                ('carbohydrates', models.FloatField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Unsaved_purchase',
            fields=[
                ('email_id', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('mfg_code', models.CharField(max_length=20)),
                ('food_id', models.IntegerField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=30)),
                ('calories', models.IntegerField()),
                ('protein', models.FloatField()),
                ('fats', models.FloatField()),
                ('carbohydrates', models.FloatField()),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
